# Generated by Django 2.2.4 on 2024-07-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_shell_app', '0002_auto_20240710_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
