# Generated by Django 2.2.4 on 2024-07-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_shell_app', '0004_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
