# Generated by Django 2.2.4 on 2024-07-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='author',
            new_name='dojo',
        ),
    ]
